[package]
name = "rust_reqwests"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
